name: Xylum
favicon: null
layout_spectrum: 0.5920043885707855
typography_spectrum: 0.7499415446072817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5624021959956735
  lightness: 0.1555101948324591
  saturation: 0.8615431059151888
  rhythmicContrast: 0.6404897312168032
purpose: []
